runtime: nodejs10

instance_class: F2

handlers:
    - url: /_next
      static_dir: .next
      secure: always

    - url: /static/(.*\.(gif|png|jpg|ico|txt))$
      static_files: static/\1
      upload: static/.*\.(gif|png|jpg|svg|ico|txt)$
      secure: always

    - url: /.*
      script: auto
      secure: always

env_variables:
    HOST: '0.0.0.0'
    NODE_ENV: 'production'
